######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 25 02:51:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hellonotepad.cpp
